name: Test casting

on:
  workflow_dispatch:

jobs:
  testllvmlite:
    name: cast on llvm lite
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install llvmlite
    - name: bitcast to float32
      run: python bitcast.py
    - name: bitcast to float32 then cast to float16 on LLVM lite
      run: python cast.py
  testllvm:
    name: cast on llvm
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install llvm
      run: sudo apt install llvm
    - name: bitcast to float32 then cast to float16 on LLVM
      run: llc -filetype=obj e.ll -o e.o && clang e.o main.c -o main -rtlib=compiler-rt && ./main
